import 'dart:developer';
import 'dart:io';

String _toCamelCase(String name) {
  final parts = name.split('-');
  return parts.first + parts.skip(1).map((p) => p[0].toUpperCase() + p.substring(1)).join();
}

void main(List<String> args) {
  final cssFile = File(args[0]);

  if (!cssFile.existsSync()) {
    log('lucide.css file not found');
    exit(0);
  }

  final content = cssFile.readAsStringSync();
  final pattern = RegExp(r'\.icon-([^:]+)::before\s*\{\s*content:\s*"\\([0-9a-fA-F]+)";\s*\}');
  final matches = pattern.allMatches(content);

  final generatedOutput = <String>[
    '// 🐦 Flutter imports:\n',
    "import 'package:flutter/widgets.dart';\n\n",
    '// 🌎 Project imports:\n',
    "import 'package:lucide_icons/src/icon_data.dart';\n\n",
    '// THIS FILE IS AUTOMATICALLY GENERATED!\n\n',
    'class LucideIcons {\n',
  ];

  for (final match in matches) {
    final name = match.group(1)!;
    final hex = match.group(2)!.toUpperCase();

    generatedOutput.add(
      '  static const IconData ${_toCamelCase(name)} = LucideIconData(0x$hex);\n',
    );

    log('$hex $name');
  }

  generatedOutput.add('}\n');

  final output = File('./lib/lucide_icons.dart');
  output.writeAsStringSync(generatedOutput.join());
}
