import 'dart:developer';
import 'dart:io';

import 'package:html/parser.dart' show parse;
import 'package:recase/recase.dart';

void main(List<String> args) {
  final fontsPreviewFile = File(args[0]);

  if (!fontsPreviewFile.existsSync()) {
    log('lucide preview file not found');
    exit(0);
  }

  final content = fontsPreviewFile.readAsStringSync();
  final c = parse(content);
  final list = c.getElementsByClassName('glyph');

  final generatedOutput = <String>[
    '// 🐦 Flutter imports:\n',
    "import 'package:flutter/widgets.dart';\n\n",
    '// 🌎 Project imports:\n',
    "import 'package:lucide_icons/src/icon_data.dart';\n\n",
    '// THIS FILE IS AUTOMATICALLY GENERATED!\n\n',
    'class LucideIcons {\n',
  ];

  for (final icon in list) {
    final name = icon.getElementsByClassName('class').first.attributes['value']!.replaceFirst('.icon-', '');
    final val = icon
        .getElementsByClassName('point')
        .first
        .attributes['value']!
        .replaceFirst('&#x', '')
        .replaceFirst(';', '');

    generatedOutput.add(
      '  static const IconData ${ReCase(name).camelCase} = LucideIconData(0x${val.toUpperCase()});\n',
    );

    log('$val $name');
  }

  generatedOutput.add('}\n');

  final output = File('./lib/lucide_icons.dart');
  output.writeAsStringSync(generatedOutput.join());
}
